% function to create a vocabulary from multiple text files under folders
function voc = buildVoc(folder, voc)

stopword = {'ourselves', 'hers', 'between', 'yourself', 'but', 'again', 'there', ...
    'about', 'once', 'during', 'out', 'very', 'having', 'with', 'they', 'own', ...
    'an', 'be', 'some', 'for', 'do', 'its', 'yours', 'such', 'into', ...
    'of', 'most', 'itself', 'other', 'off', 'is', 's', 'am', 'or', ...
    'who', 'as', 'from', 'him', 'each', 'the', 'themselves', 'until', ...
    'below', 'are', 'we', 'these', 'your', 'his', 'through', 'don', 'nor', ...
    'me', 'were', 'her', 'more', 'himself', 'this', 'down', 'should', 'our', ...
    'their', 'while', 'above', 'both', 'up', 'to', 'ours', 'had', 'she', 'all', ...
    'no', 'when', 'at', 'any', 'before', 'them', 'same', 'and', 'been', 'have', ...
    'in', 'will', 'on', 'does', 'yourselves', 'then', 'that', 'because', ...
    'what', 'over', 'why', 'so', 'can', 'did', 'not', 'now', 'under', 'he', ...
    'you', 'herself', 'has', 'just', 'where', 'too', 'only', 'myself', ...
    'which', 'those', 'i', 'after', 'few', 'whom', 't', 'being', 'if', ...
    'theirs', 'my', 'against', 'a', 'by', 'doing', 'it', 'how', ...
    'further', 'was', 'here', 'than'}; % define English stop words, from NLTK



files = dir(fullfile(folder,'*.txt'));
%files = dir(fullfile('C:','Users','Kahlil','Desktop','College','CSE 408','Project1','P1','Data''*.txt'));
for file = files'
    [fid, msg] = fopen(fullfile(folder,file.name), 'rt', 'n','UTF-8');
    error(msg);
    line = fgets(fid); % Get the first line from
     % the file.
    while line ~= -1
        %PUT YOUR IMPLEMENTATION HERE
        replace = '[^.,!]';
        after = regexp(line,replace);
        line = line(after);
        [token,remain]= strtok(line);
        temp = ismember(lower(token), stopword);
        if temp ~= 1
            voc{1,end+1}=lower(token);  
            line = remain;
        end
        line = remain;
    end
    voc = unique(voc);
fclose(fid);
end